/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import BD.Conexion;
import Clases.Categoria;
import Clases.TipoSocio;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nacho
 */
public class AbmCategorias extends javax.swing.JPanel {

    /**
     * Creates new form PanelVacio
     */
    Categoria cat;
    Principal main;
    public AbmCategorias(Principal main) {
        initComponents();
        this.main = main;
        cargarCat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tCategorias = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sMin = new javax.swing.JSpinner();
        sMax = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        tCategorias.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad Min.", "Edad Max."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tCategoriasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tCategorias);

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Categorías");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Edad min:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Edad max:");

        sMin.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        sMax.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sMax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                        .addComponent(sMin, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(95, 95, 95)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnAgregar)
                            .addComponent(btnModificar))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tCategoriasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tCategoriasMousePressed
        // TODO add your handling code here:
        if(tCategorias.getSelectedRowCount()==1){
            cat = (Categoria) tCategorias.getValueAt(tCategorias.getSelectedRow(), 0);
        }
    }//GEN-LAST:event_tCategoriasMousePressed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(btnAgregar.getText().equals("Agregar")){
            Categoria ts = new Categoria();
            ts.setNombre(tfNombre.getText());
            ts.setEdadMin((int) sMin.getValue());
            ts.setEdadMax((int) sMax.getValue());
            ts.setVigente(true);
            if(verificarEdades(ts)){
                Conexion.getInstance().persist(ts);
                tfNombre.setText("");
                sMin.setValue(0);
                sMax.setValue(0);
                main.categorias  = Conexion.getInstance().getCategorias();
                cargarCat();
                limpiar();
            }
        }
        else{
            cat.setNombre(tfNombre.getText());
            cat.setEdadMin((int)sMin.getValue());
            cat.setEdadMax((int)sMax.getValue());
            btnAgregar.setText("Agregar");
            btnEliminar.setText("Eliminar");
            Conexion.getInstance().merge(cat);
            main.categorias = Conexion.getInstance().getCategorias();
            cargarCat();
            limpiar();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    public boolean verificarEdades(Categoria nueva){
        Iterator<Categoria> it = main.categorias.iterator();
        while (it.hasNext()) {
            Categoria s = it.next();
            if(s.isVigente() && ((s.getEdadMax()>= nueva.getEdadMin() && s.getEdadMin() <= nueva.getEdadMin()) || (s.getEdadMax()>= nueva.getEdadMax() && s.getEdadMin() <= nueva.getEdadMax()))) {
                JOptionPane.showMessageDialog(this, "Error con las edad, verificar que no haya incompatibilidad con otras categorias.", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if((int)sMin.getValue() <= (int)sMax.getValue())
                JOptionPane.showMessageDialog(this, "Error con las edad, la edad máxima no puede ser menor o igual a la mínima.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return true;
    }
    
    public void cargarCat(){
        Iterator<Categoria> it = main.categorias.iterator();
        DefaultTableModel mdl = (DefaultTableModel) tCategorias.getModel();
        mdl.setRowCount(0);
        while (it.hasNext()) {
            Categoria s = it.next();
            if (s.isVigente()) {  
                Object[] fila = new Object[3];
                fila[0] = s;
                fila[1] = s.getEdadMin();
                fila[2] = s.getEdadMax();
                mdl.addRow(fila); 
            }
        }
    }
    public void limpiar(){
        tfNombre.setText("");
        sMin.setValue(0);
        sMax.setValue(0);
        cat = null;
        tCategorias.clearSelection();
    }
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(btnEliminar.getText().equals("Eliminar")){
            if(cat != null){
                cat.setVigente(false);
                Conexion.getInstance().merge(cat);
                main.categorias = Conexion.getInstance().getCategorias();
                cargarCat();
                limpiar();
            }
        }
        else{
            btnAgregar.setText("Agregar");
            btnEliminar.setText("Eliminar");
            limpiar();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(cat != null){
            btnAgregar.setText("Confirmar");
            btnEliminar.setText("Cancelar");
            tfNombre.setText(cat.getNombre());
            sMin.setValue(cat.getEdadMin());
            sMax.setValue(cat.getEdadMax());
        }

    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner sMax;
    private javax.swing.JSpinner sMin;
    private javax.swing.JTable tCategorias;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
