/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import BD.Conexion;
import Clases.Actividad;
import Clases.Cuota;
import Clases.Familia;
import Clases.Jugador;
import Clases.Socio;
import Clases.TipoSocio;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nacho
 */
public class AltaSocio extends javax.swing.JPanel {

    /**
     * Creates new form GUIABMSocios
     */
    Familia f;
    Principal main;
    Socio sel;
    public AltaSocio(Principal main, Familia f) {
        initComponents();
        //panelJugador.setVisible(false);
        panelJugador.setEnabled(false);
        panelFamilia.setEnabled(false);
        this.main = main;
        this.f = f;
        /*if(f!=null){
            cargarFamiliares();
            cbFamilia.setSelectedIndex(1);
        }
        else{
            cbFamilia.enable(false);
        }*/
            
        dcFechaIngreso.setDate(new Date());
        List<TipoSocio> ts;
        ts = Conexion.getInstance().getTiposSocios();
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        for(TipoSocio tipo: ts){
            if(tipo.isVigente()){
                dcm.addElement(tipo);
            }
        }
        cbTipoSocio.setModel(dcm);
        jugador(false);
        
        
        List<Cuota> cuotas;
        cuotas = Conexion.getInstance().getCuotas();
        DefaultComboBoxModel dcm2 = new DefaultComboBoxModel();
        for(Cuota tipo: cuotas){
                if(tipo.isVigente()){
                        dcm2.addElement(tipo);
                }
        }
        cbCuotas.setModel(dcm2);
    
    }
    
    public void cargarFamiliares(){
        Conexion.getInstance().refresh(f);
        Iterator<Socio> it = f.getSocios().iterator();
        DefaultTableModel mdl = (DefaultTableModel) tFamiliares.getModel();
        mdl.setRowCount(0);
        while (it.hasNext()) {
            Socio s = it.next();
            if (s.isVigente()) {  
                Object[] fila = new Object[4];
                fila[0] = s;
                fila[1] = s.getApellido();
                fila[2] = s.getFechaNac();
                fila[3] = s.getRol();
                mdl.addRow(fila); 
            }
        }
        /*
        if(mdl.getRowCount()>0)
            cbFamilia.enable(true);
        */
    }
    public void jugador(boolean b){
        lCarnet.setVisible(b);
        dcCarnetHab.setVisible(b);
        lPlantel.setVisible(b);
        tfPlantel.setVisible(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        dcFechaNac = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        tfCI = new javax.swing.JTextField();
        lCarnet1 = new javax.swing.JLabel();
        dcFechaIngreso = new com.toedter.calendar.JDateChooser();
        cbTipoSocio = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbCuotas = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        checkJ = new javax.swing.JCheckBox();
        panelJugador = new javax.swing.JPanel();
        lPlantel = new javax.swing.JLabel();
        tfPlantel = new javax.swing.JTextField();
        panelC = new javax.swing.JPanel();
        dcCarnetHab = new com.toedter.calendar.JDateChooser();
        cbTipoCarnet = new javax.swing.JComboBox<>();
        lTipoCarnet = new javax.swing.JLabel();
        lVenCarnet = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dcFechaNac1 = new com.toedter.calendar.JDateChooser();
        panelFamilia = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tFamiliares = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        checkF = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Alta Socio");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Cédula:");

        tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Apellido:");

        tfApellido.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        tfTelefono.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Teléfono:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Dirección:");

        tfDireccion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Fecha Nac.");

        tfCI.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCIActionPerformed(evt);
            }
        });
        tfCI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCIKeyPressed(evt);
            }
        });

        lCarnet1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lCarnet1.setText("Fecha ingreso:");

        cbTipoSocio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbTipoSocio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Común", "Jugador", "Vitalicio", "Contribuyente", " " }));
        cbTipoSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoSocioActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setText("Tipo socio:");

        cbCuotas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbCuotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Común", "Jugador", "Vitalicio", "Contribuyente", " " }));
        cbCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCuotasActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setText("Cuota:");

        checkJ.setBackground(new java.awt.Color(255, 255, 255));
        checkJ.setText("Jugador");
        checkJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkJActionPerformed(evt);
            }
        });

        panelJugador.setBackground(new java.awt.Color(255, 255, 255));
        panelJugador.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador"));
        panelJugador.setToolTipText("Jugador");
        panelJugador.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lPlantel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lPlantel.setText("Plantel:");

        tfPlantel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        panelC.setBackground(new java.awt.Color(255, 255, 255));
        panelC.setBorder(javax.swing.BorderFactory.createTitledBorder("Carnet Habilitante"));
        panelC.setToolTipText("Carnet Habilitante");
        panelC.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        panelC.setName("Carnet Habilitante"); // NOI18N

        cbTipoCarnet.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbTipoCarnet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carnet de Salud", "Carnet del niño", "Carnet del adolescente" }));
        cbTipoCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoCarnetActionPerformed(evt);
            }
        });

        lTipoCarnet.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lTipoCarnet.setText("Tipo:");

        lVenCarnet.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lVenCarnet.setText("Vecimiento:");

        javax.swing.GroupLayout panelCLayout = new javax.swing.GroupLayout(panelC);
        panelC.setLayout(panelCLayout);
        panelCLayout.setHorizontalGroup(
            panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTipoCarnet)
                    .addComponent(lVenCarnet))
                .addGap(48, 48, 48)
                .addGroup(panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTipoCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcCarnetHab, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCLayout.setVerticalGroup(
            panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCLayout.createSequentialGroup()
                        .addGroup(panelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipoCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lTipoCarnet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dcCarnetHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addComponent(lVenCarnet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setText("Ven. Cédula:");

        javax.swing.GroupLayout panelJugadorLayout = new javax.swing.GroupLayout(panelJugador);
        panelJugador.setLayout(panelJugadorLayout);
        panelJugadorLayout.setHorizontalGroup(
            panelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugadorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelJugadorLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(lPlantel)
                            .addGap(72, 72, 72)
                            .addComponent(tfPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelJugadorLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel14)
                            .addGap(45, 45, 45)
                            .addComponent(dcFechaNac1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelJugadorLayout.setVerticalGroup(
            panelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJugadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPlantel)
                    .addComponent(tfPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcFechaNac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        panelFamilia.setBackground(new java.awt.Color(255, 255, 255));
        panelFamilia.setBorder(javax.swing.BorderFactory.createTitledBorder("Familiares"));

        tFamiliares.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tFamiliares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Nacimiento", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tFamiliares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tFamiliaresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tFamiliares);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton2.setText("Quitar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFamiliaLayout = new javax.swing.GroupLayout(panelFamilia);
        panelFamilia.setLayout(panelFamiliaLayout);
        panelFamiliaLayout.setHorizontalGroup(
            panelFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFamiliaLayout.createSequentialGroup()
                .addGroup(panelFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFamiliaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFamiliaLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFamiliaLayout.setVerticalGroup(
            panelFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFamiliaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );

        checkF.setBackground(new java.awt.Color(255, 255, 255));
        checkF.setText("Familia");
        checkF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lCarnet1)
                            .addGap(35, 35, 35)
                            .addComponent(dcFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnAgregar)
                            .addGap(80, 80, 80))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel9)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfCI, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dcFechaNac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTipoSocio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(checkJ))
                    .addComponent(checkF))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lCarnet1))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(cbTipoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(btnAgregar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkJ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkF)))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCIActionPerformed

    private void tfCIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCIKeyPressed
        // TODO add your handling code here:
        if(evt.equals("a"))
            evt.consume();
    }//GEN-LAST:event_tfCIKeyPressed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
         
        if(cbTipoSocio.getSelectedItem().toString().equals("Jugador")){
            Jugador j = new Jugador();
            j.setNombre(tfNombre.getText());
            j.setApellido(tfApellido.getText());
            j.setCi(parseInt(tfCI.getText()));
            j.setDireccion(tfDireccion.getText());
            j.setFechaNac(dcFechaNac.getDate());
            j.setTelefono(tfTelefono.getText());
            
            j.setFechaIngreso(dcFechaIngreso.getDate());
            j.setTipo((TipoSocio)cbTipoSocio.getSelectedItem());
            j.setVigente(true);
            j.setCarnetHabilitante(dcCarnetHab.getDate());
            j.setPlantel(tfPlantel.getText());
            j.setRol(cbFamilia.getSelectedItem().toString());
            if(cbFamilia.getSelectedIndex()==1){
                Conexion.getInstance().refresh(f);
                if(f.getSocios().size()<4){// es un número variable
                    j.setFamilia(f);
                    Conexion.getInstance().persist(j);
                }
                else
                    System.out.println("Familia llena");
            }
            else{
                Conexion.getInstance().persist(j);
                f = new Familia();
                List<Socio> ls = new ArrayList<Socio>();
                ls.add(j);
                f.setSocios(ls);
                Conexion.getInstance().persist(f);
                j.setFamilia(f);
                Conexion.getInstance().merge(j);
                Conexion.getInstance().refresh(j);
            }
                
            /*Conexion.getInstance().persist(j);
            
            if(f==null){//FALTA VERIFICAR LA CANTIDAD DE MIEMBROS
                f = new Familia();
                List<Socio> ls = new ArrayList<Socio>();
                ls.add(j);
                f.setSocios(ls);
                Conexion.getInstance().persist(f);
                j.setFamilia(f);
                Conexion.getInstance().merge(j);
                Conexion.getInstance().refresh(j);
            }
            else{
                j.setFamilia(f);
                Conexion.getInstance().merge(j);
            }*/
        }
        else{
            Socio j = new Socio();
            j.setNombre(tfNombre.getText());
            j.setApellido(tfApellido.getText());
            j.setCi(parseInt(tfCI.getText()));
            j.setDireccion(tfDireccion.getText());
            j.setFechaNac(dcFechaNac.getDate());
            j.setTelefono(tfTelefono.getText());
            j.setFechaIngreso(dcFechaIngreso.getDate());
            j.setTipo((TipoSocio)cbTipoSocio.getSelectedItem());
            j.setVigente(true);
            
            if(f!=null){
                Conexion.getInstance().refresh(f);
                if(f.getSocios().size()<4){// es un número variable
                    j.setFamilia(f);
                    Conexion.getInstance().persist(j);
                }
                else
                    System.out.println("Familia llena");
            }
            else{
                Conexion.getInstance().persist(j);
                f = new Familia();
                List<Socio> ls = new ArrayList<Socio>();
                ls.add(j);
                f.setSocios(ls);
                Conexion.getInstance().persist(f);
                j.setFamilia(f);
                Conexion.getInstance().merge(j);
                Conexion.getInstance().refresh(j);

            }
            /*if(f!=null){
                Conexion.getInstance().refresh(f);
                if(f.getSocios().size()<4){// es un número variable
                    j.setFamilia(f);
                }
                else
                    System.out.println("Familia llena");
            }
                
            Conexion.getInstance().persist(j);
            
            if(f==null){ //FALTA VERIFICAR LA CANTIDAD DE MIEMBROS
                f = new Familia();
                List<Socio> ls = new ArrayList<Socio>();
                ls.add(j);
                f.setSocios(ls);
                Conexion.getInstance().persist(f);
                j.setFamilia(f);
                Conexion.getInstance().merge(j);
                Conexion.getInstance().refresh(j);
            }
            else{
                j.setFamilia(f);
                Conexion.getInstance().merge(j);
            }*/
        }
        cargarFamiliares();
        limpiar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(sel != null){
            sel.setFamilia(null);
            Conexion.getInstance().merge(sel);
            cargarFamiliares();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbTipoSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoSocioActionPerformed
        // TODO add your handling code here:
        if(cbTipoSocio.getSelectedItem().toString().equals("Jugador"))
            jugador(true);
        else
            jugador(false);
    }//GEN-LAST:event_cbTipoSocioActionPerformed

    private void tFamiliaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tFamiliaresMouseClicked
        // TODO add your handling code here:
        if(tFamiliares.getSelectedRowCount()==1)
            sel = (Socio) tFamiliares.getValueAt(tFamiliares.getSelectedRow(), 0);
    }//GEN-LAST:event_tFamiliaresMouseClicked

    private void cbCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCuotasActionPerformed

    private void checkJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkJActionPerformed
        // TODO add your handling code here:
        if(checkJ.isSelected())
            panelJugador.setEnabled(true);
        else
            panelJugador.setEnabled(false);
    }//GEN-LAST:event_checkJActionPerformed

    private void cbTipoCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoCarnetActionPerformed

    private void checkFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFActionPerformed
        // TODO add your handling code here:
        if(checkF.isSelected())
            panelFamilia.setEnabled(true);
        else
            panelFamilia.setEnabled(false);
    }//GEN-LAST:event_checkFActionPerformed

    public void limpiar(){
        tfNombre.setText("");
        tfApellido.setText("");
        tfDireccion.setText("");
        tfTelefono.setText("");
        tfPlantel.setText("");
        tfCI.setText("");
        dcFechaNac.setDate(null);
        dcCarnetHab.setDate(null);
    }
    /*public static boolean esCIValida(String ci) {
        if(ci.length() != 7 && ci.length() != 8){
        return false;
        }else{
        try{
        Integer.parseInt(ci);
        }catch (NumberFormatException e){
        return false;
        }
        }

        int digVerificador = Integer.parseInt((ci.charAt(ci.length() - 1)) + "" ) ;
        int[] factores;
        if(ci.length() == 7){ // CI viejas
        factores = new int[]{9, 8, 7, 6, 3, 4};
        }else{
        factores = new int[]{2, 9, 8, 7, 6, 3, 4};
        }


        int suma = 0;
        for(int i=0; i int digito = Integer.parseInt(ci.charAt(i) + "") ;
        suma += digito * factores[ i ];
    

        int resto = suma % 10;
        int checkdigit = 10 - resto;

        if(checkdigit == 10){
        return (digVerificador == 0);
        }
        else {
        return (checkdigit == digVerificador) ;
        }
    }*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cbCuotas;
    private javax.swing.JComboBox<String> cbTipoCarnet;
    private javax.swing.JComboBox<String> cbTipoSocio;
    private javax.swing.JCheckBox checkF;
    private javax.swing.JCheckBox checkJ;
    private com.toedter.calendar.JDateChooser dcCarnetHab;
    private com.toedter.calendar.JDateChooser dcFechaIngreso;
    private com.toedter.calendar.JDateChooser dcFechaNac;
    private com.toedter.calendar.JDateChooser dcFechaNac1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lCarnet1;
    private javax.swing.JLabel lPlantel;
    private javax.swing.JLabel lTipoCarnet;
    private javax.swing.JLabel lVenCarnet;
    private javax.swing.JPanel panelC;
    private javax.swing.JPanel panelFamilia;
    private javax.swing.JPanel panelJugador;
    private javax.swing.JTable tFamiliares;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCI;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPlantel;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
