/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import BD.Conexion;
import Clases.Actividad;
import Clases.Cuota;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nacho
 */
public class AltaCuota extends javax.swing.JPanel {

    /**
     * Creates new form PanelVacio
     */
    Cuota sel = null;
    Principal main;
    //List<Cuota> cuotas;
    public AltaCuota(Principal main) {
        initComponents();
        dcFecha.setDate(new Date());
        lMod.setVisible(false);
        btnCancelar.setVisible(false);
        //cuotas = Conexion.getInstance().getCuotas();
        this.main = main;
        cargarCuotas();
        cargarAct();
        tfBuscar.setText("Buscar");
    }

    
    public void cargarCuotas(){
        Iterator<Cuota> it = main.cuotas.iterator();
        DefaultTableModel mdl = (DefaultTableModel) tCuotas.getModel();
        mdl.setRowCount(0);
        while (it.hasNext()) {
            Cuota s = it.next();
            if (s.isVigente()) {  
                Object[] fila = new Object[5];
                fila[0] = main.sdf.format(s.getFecha());
                fila[1] = s;
                fila[2] = s.getMonto();
                fila[3] = s.getDescripcion();
                fila[4] = s.getFrecuencia();
                mdl.addRow(fila); 
            }
        }
    }
    public void cargarAct(){
        List<Actividad> acts = main.actividades;
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        dcm.addElement("Ninguna");
        for(Actividad tipo: acts){
            if(tipo.isVigente()){
                dcm.addElement(tipo);
            }
        }
        cbActividades.setModel(dcm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lPlantel = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        lCarnet1 = new javax.swing.JLabel();
        dcFecha = new com.toedter.calendar.JDateChooser();
        lPlantel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDesc = new javax.swing.JTextArea();
        lPlantel2 = new javax.swing.JLabel();
        lPlantel3 = new javax.swing.JLabel();
        cbFrec = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tCuotas = new javax.swing.JTable();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        lMod = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        tfBuscar = new javax.swing.JTextField();
        lPlantel4 = new javax.swing.JLabel();
        cbActividades = new javax.swing.JComboBox<>();
        sMonto = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cuotas");

        lPlantel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lPlantel.setText("Nombre:");

        tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lCarnet1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lCarnet1.setText("Fecha:");

        lPlantel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lPlantel1.setText("Monto:");

        taDesc.setColumns(20);
        taDesc.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        taDesc.setRows(5);
        jScrollPane1.setViewportView(taDesc);

        lPlantel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lPlantel2.setText("Descripción:");

        lPlantel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lPlantel3.setText("Frecuencia:");

        cbFrec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensual", "Anual" }));

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tCuotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Nombre", "Monto", "Descripción", "Frecuencia"
            }
        ));
        tCuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tCuotasMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tCuotas);

        btnBorrar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        lMod.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lMod.setText("Modificando:");

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tfBuscar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfBuscarFocusLost(evt);
            }
        });
        tfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBuscarKeyReleased(evt);
            }
        });

        lPlantel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lPlantel4.setText("Actividad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(657, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(btnModificar)
                        .addGap(98, 98, 98)
                        .addComponent(btnBorrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)
                                .addGap(122, 122, 122))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lCarnet1)
                                            .addComponent(lPlantel)
                                            .addComponent(lPlantel1)
                                            .addComponent(lPlantel2)
                                            .addComponent(lPlantel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbFrec, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(sMonto, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(lMod))
                                    .addComponent(lPlantel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(cbActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMod)
                    .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lCarnet1)
                                .addGap(18, 18, 18)
                                .addComponent(lPlantel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lPlantel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lPlantel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lPlantel3)
                                    .addComponent(cbFrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(sMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lPlantel4)
                            .addComponent(cbActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnModificar)
                    .addComponent(btnAgregar)
                    .addComponent(btnCancelar))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(btnAgregar.getText().equals("Agregar")){
            if((int)sMonto.getValue() <=0)
                JOptionPane.showMessageDialog(this, "El monto no puede ser menor o igual a 0.", "Error", JOptionPane.ERROR_MESSAGE);
            else if(tfNombre.getText().equals(""))
                JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            else if(dcFecha.getDate()==null)
                JOptionPane.showMessageDialog(this, "La fecha no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
            else{
                Cuota c = new Cuota();
                c.setMonto((int)sMonto.getValue());
                c.setNombre(tfNombre.getText());
                c.setFecha(dcFecha.getDate());
                c.setDescripcion(taDesc.getText());
                c.setFrecuencia(cbFrec.getSelectedItem().toString());
                c.setVigente(true);
                if(cbActividades.getSelectedIndex()!=0)
                    c.setActividad((Actividad)  cbActividades.getSelectedItem());
                Conexion.getInstance().persist(c);
                main.cuotas.add(c);
                cargarCuotas();
                JOptionPane.showMessageDialog(this, "Cuota agregada con éxito.", "Información", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            }
        }
        else{
            if((int)sMonto.getValue() <=0)
                JOptionPane.showMessageDialog(this, "El monto no puede ser menor o igual a 0.", "Error", JOptionPane.ERROR_MESSAGE);
            else if(tfNombre.getText().equals(""))
                JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            else if(dcFecha.getDate()==null)
                JOptionPane.showMessageDialog(this, "La fecha no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
            else{
                sel.setMonto((int)sMonto.getValue());
                sel.setNombre(tfNombre.getText());
                sel.setFecha(dcFecha.getDate());
                sel.setDescripcion(taDesc.getText());
                sel.setFrecuencia(cbFrec.getSelectedItem().toString());
                if(cbActividades.getSelectedIndex()!=0)
                    sel.setActividad((Actividad)cbActividades.getSelectedItem());
                else
                    sel.setActividad(null);
                Conexion.getInstance().merge(sel);
                main.cuotas.set(main.cuotas.indexOf(sel),sel);
                cargarCuotas();
                tfNombre.setEditable(true);
                JOptionPane.showMessageDialog(this, "Cuota "+sel.getNombre()+" modificada.", "Información", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            }
            
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        if(sel!=null){
            sel.setVigente(false);
            Conexion.getInstance().merge(sel);
            cargarCuotas();
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(sel!=null){
            lMod.setVisible(true);
            btnCancelar.setVisible(true);
            btnAgregar.setText("Confirmar");
            sMonto.setValue(sel.getMonto());
            tfNombre.setText(sel.getNombre());
            tfNombre.setEditable(false);
            taDesc.setText(sel.getDescripcion());
            if(sel.getActividad()==null)
                cbActividades.setSelectedIndex(0);
            else
                cbActividades.setSelectedItem(sel.getActividad());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tCuotasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tCuotasMousePressed
        // TODO add your handling code here:
        if(tCuotas.getSelectedRowCount()==1)
            sel = (Cuota) tCuotas.getValueAt(tCuotas.getSelectedRow(), 1);
    }//GEN-LAST:event_tCuotasMousePressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tfBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarKeyReleased
        // TODO add your handling code here:
        if(tfBuscar.getText().equals("")){
            cargarCuotas();
        }
        else
            buscarCuotas(tfBuscar.getText());
    }//GEN-LAST:event_tfBuscarKeyReleased

    private void tfBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBuscarFocusGained
        // TODO add your handling code here:
        if(tfBuscar.getText().trim().equals("Buscar")){
            tfBuscar.setText("");
        }
    }//GEN-LAST:event_tfBuscarFocusGained

    private void tfBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBuscarFocusLost
        // TODO add your handling code here:
        if(tfBuscar.getText().trim().equals("")){
            tfBuscar.setText("Buscar");
        }
    }//GEN-LAST:event_tfBuscarFocusLost
    public void buscarCuotas(String buscar){
        DefaultTableModel mdl = (DefaultTableModel) tCuotas.getModel();
        Iterator<Cuota> it = main.cuotas.iterator();
        mdl.setRowCount(0);
        while (it.hasNext()) {
            Cuota s = it.next();
            if (s.isVigente() && (s.getNombre().toUpperCase().contains(buscar.toUpperCase()) || s.getDescripcion().toUpperCase().contains(buscar.toUpperCase()))) {  
                Object[] fila = new Object[5];
                fila[0] = Conexion.sdf.format(s.getFecha());
                fila[1] = s;
                fila[2] = s.getMonto();
                fila[3] = s.getDescripcion();
                fila[4] = s.getFrecuencia();
                mdl.addRow(fila);
            }
        }
    }
    public void limpiar(){
        dcFecha.setDate(new Date());
        tfNombre.setText("");
        sMonto.setValue(0);
        taDesc.setText("");
        tCuotas.clearSelection();
        cbActividades.setSelectedIndex(0);
        cbFrec.setSelectedIndex(0);
        btnCancelar.setVisible(false);
        btnAgregar.setText("Agregar");
        lMod.setVisible(false);
        tfNombre.setEditable(true);
        sel = null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbActividades;
    private javax.swing.JComboBox<String> cbFrec;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lCarnet1;
    private javax.swing.JLabel lMod;
    private javax.swing.JLabel lPlantel;
    private javax.swing.JLabel lPlantel1;
    private javax.swing.JLabel lPlantel2;
    private javax.swing.JLabel lPlantel3;
    private javax.swing.JLabel lPlantel4;
    private javax.swing.JSpinner sMonto;
    private javax.swing.JTable tCuotas;
    private javax.swing.JTextArea taDesc;
    private javax.swing.JTextField tfBuscar;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
