/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import BD.Conexion;
import Clases.Actividad;
import Clases.Categoria;
import Clases.Cuota;
import Clases.Familia;
import Clases.Jugador;
import Clases.PagoBBC;
import Clases.Socio;
import Clases.SocioActividad;
import Clases.TipoSocio;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nacho
 */
public class DetallesSocio extends javax.swing.JPanel {

    /**
     * Creates new form GUIABMSocios
     */
    Principal main;
    Jugador j;
    Socio s;
    public DetallesSocio(Principal main, Socio s) {
        initComponents();
        this.main = main;
        this.s  = s;
        load();
    }
    
    public void load(){
        Conexion.getInstance().refresh(s);
        dcFechaIngreso.setDate(s.getFechaIngreso());
        tfCI.setText(String.valueOf(s.getCi()));
        tfCI.setEditable(false);
        tfNombre.setText(s.getNombre());
        tfApellido.setText(s.getApellido());
        
        tfTelefono.setText(s.getTelefono());
        tfDireccion.setText(s.getDireccion());
        dcFechaNac.setDate(s.getFechaNac());
        
        cargarTipos();
        cbTipoSocio.setSelectedItem(s.getTipo());

        j = Conexion.getInstance().findJugador(s.getCi());
        if(j == null){
            for(Component component : pJugador.getComponents()) {
                component.setEnabled(false);
            }
            taDesc.setEditable(false);
            jTabbedPane1.setSelectedIndex(1);
            loadAct();
        }
        else
            loadJugador();
    }
    

    
    public void cargarTipos(){
        List<TipoSocio> ts;
        ts = Conexion.getInstance().getTiposSocios();
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        for(TipoSocio tipo: ts){
                if(tipo.isVigente()){
                        dcm.addElement(tipo);
                }
        }
        cbTipoSocio.setModel(dcm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfCI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        dcFechaNac = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        lCarnet1 = new javax.swing.JLabel();
        dcFechaIngreso = new com.toedter.calendar.JDateChooser();
        btnActualizar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pJugador = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cbCat = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cbTipoCarnet = new javax.swing.JComboBox<>();
        dcVenCarnet = new com.toedter.calendar.JDateChooser();
        dcVenCi = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnActualizarJugador = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        taDesc = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        pActividades = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnAgregarActividad = new javax.swing.JButton();
        btnBorrarActividad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tActividades = new javax.swing.JTable();
        btnModificarActividad = new javax.swing.JButton();
        pFamilia = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tFamiliares = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        btnAgregarExistente = new javax.swing.JButton();
        btnEliminarFamiliar = new javax.swing.JButton();
        btnAgregarNuevoF = new javax.swing.JButton();
        tfCi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnDetallesFamiliar = new javax.swing.JButton();
        pCuotas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tCuotas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnEliminarCuotaDeSocio = new javax.swing.JButton();
        cbCuotas = new javax.swing.JComboBox<>();
        btnAgregarCuota = new javax.swing.JButton();
        pPagos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tPagos = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        mc = new com.toedter.calendar.JMonthChooser();
        yc = new com.toedter.calendar.JYearChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        sMonto = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lCarnet2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbTipoSocio = new javax.swing.JComboBox<>();
        btnEliminarSocio = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        tfCI.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCIActionPerformed(evt);
            }
        });
        tfCI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCIKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Detalles socio");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Cédula:");

        tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Apellido:");

        tfApellido.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        tfTelefono.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Teléfono:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Dirección:");

        tfDireccion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Fecha Nac.");

        lCarnet1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lCarnet1.setText("Fecha ingreso:");

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        pJugador.setBackground(new java.awt.Color(255, 255, 255));
        pJugador.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setText("Categoría:");

        cbCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCatActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setText("Carmet de:");

        cbTipoCarnet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salud", "Adolescente", "Niño" }));
        cbTipoCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoCarnetActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setText("Ven. carnet:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel18.setText("Ven. Cédula:");

        btnActualizarJugador.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnActualizarJugador.setText("Actualizar");
        btnActualizarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarJugadorActionPerformed(evt);
            }
        });

        taDesc.setColumns(20);
        taDesc.setRows(5);
        jScrollPane5.setViewportView(taDesc);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setText("Información:");

        javax.swing.GroupLayout pJugadorLayout = new javax.swing.GroupLayout(pJugador);
        pJugador.setLayout(pJugadorLayout);
        pJugadorLayout.setHorizontalGroup(
            pJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJugadorLayout.createSequentialGroup()
                .addGroup(pJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pJugadorLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btnActualizarJugador))
                    .addGroup(pJugadorLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(pJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pJugadorLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbCat, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pJugadorLayout.createSequentialGroup()
                                .addGroup(pJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(45, 45, 45)
                                .addGroup(pJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dcVenCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTipoCarnet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dcVenCi, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(pJugadorLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        pJugadorLayout.setVerticalGroup(
            pJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJugadorLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(pJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pJugadorLayout.createSequentialGroup()
                        .addGroup(pJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(pJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipoCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addComponent(dcVenCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(pJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcVenCi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnActualizarJugador)
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Info. Jugador", pJugador);

        pActividades.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Actividades");

        btnAgregarActividad.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAgregarActividad.setText("Agregra");
        btnAgregarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActividadActionPerformed(evt);
            }
        });

        btnBorrarActividad.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnBorrarActividad.setText("Borrar");
        btnBorrarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActividadActionPerformed(evt);
            }
        });

        tActividades.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Días", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tActividades);

        btnModificarActividad.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnModificarActividad.setText("Modificar");
        btnModificarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pActividadesLayout = new javax.swing.GroupLayout(pActividades);
        pActividades.setLayout(pActividadesLayout);
        pActividadesLayout.setHorizontalGroup(
            pActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pActividadesLayout.createSequentialGroup()
                .addGap(0, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(pActividadesLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pActividadesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarActividad)
                .addGap(32, 32, 32)
                .addComponent(btnModificarActividad)
                .addGap(28, 28, 28)
                .addComponent(btnBorrarActividad)
                .addGap(81, 81, 81))
        );
        pActividadesLayout.setVerticalGroup(
            pActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pActividadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarActividad)
                    .addComponent(btnBorrarActividad)
                    .addComponent(btnModificarActividad))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actividades", pActividades);

        pFamilia.setBackground(new java.awt.Color(255, 255, 255));

        tFamiliares.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tFamiliares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Nacimiento", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tFamiliares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tFamiliaresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tFamiliares);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Familiares");

        btnAgregarExistente.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAgregarExistente.setText("Agregar existente");
        btnAgregarExistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarExistenteActionPerformed(evt);
            }
        });

        btnEliminarFamiliar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEliminarFamiliar.setText("Eliminar");
        btnEliminarFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFamiliarActionPerformed(evt);
            }
        });

        btnAgregarNuevoF.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAgregarNuevoF.setText("Agregar nuevo");
        btnAgregarNuevoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNuevoFActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setText("Ci:");

        btnDetallesFamiliar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnDetallesFamiliar.setText("Deatalles");
        btnDetallesFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesFamiliarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFamiliaLayout = new javax.swing.GroupLayout(pFamilia);
        pFamilia.setLayout(pFamiliaLayout);
        pFamiliaLayout.setHorizontalGroup(
            pFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFamiliaLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(pFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pFamiliaLayout.createSequentialGroup()
                            .addComponent(btnAgregarExistente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfCi, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(btnEliminarFamiliar))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pFamiliaLayout.createSequentialGroup()
                        .addComponent(btnAgregarNuevoF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDetallesFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
            .addGroup(pFamiliaLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pFamiliaLayout.setVerticalGroup(
            pFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFamiliaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarExistente)
                    .addComponent(btnEliminarFamiliar)
                    .addComponent(tfCi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarNuevoF)
                    .addComponent(btnDetallesFamiliar))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Familia", pFamilia);

        pCuotas.setBackground(new java.awt.Color(255, 255, 255));

        tCuotas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tCuotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Nombre", "Descipción", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tCuotas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCuotasKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tCuotas);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Cuotas");

        btnEliminarCuotaDeSocio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEliminarCuotaDeSocio.setText("Eliminar");
        btnEliminarCuotaDeSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCuotaDeSocioActionPerformed(evt);
            }
        });

        cbCuotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAgregarCuota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAgregarCuota.setText("Agregar");
        btnAgregarCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCuotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCuotasLayout = new javax.swing.GroupLayout(pCuotas);
        pCuotas.setLayout(pCuotasLayout);
        pCuotasLayout.setHorizontalGroup(
            pCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCuotasLayout.createSequentialGroup()
                .addGroup(pCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCuotasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(pCuotasLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pCuotasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnAgregarCuota)
                .addGap(18, 18, 18)
                .addComponent(cbCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnEliminarCuotaDeSocio)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        pCuotasLayout.setVerticalGroup(
            pCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCuotasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(pCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCuota)
                    .addComponent(btnEliminarCuotaDeSocio))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cuotas", pCuotas);

        pPagos.setBackground(new java.awt.Color(255, 255, 255));

        tPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPagosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tPagos);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Pagos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo pago"));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setText("Monto:");

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(sMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        lCarnet2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lCarnet2.setText("Fecha:");

        javax.swing.GroupLayout pPagosLayout = new javax.swing.GroupLayout(pPagos);
        pPagos.setLayout(pPagosLayout);
        pPagosLayout.setHorizontalGroup(
            pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPagosLayout.createSequentialGroup()
                .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPagosLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pPagosLayout.createSequentialGroup()
                        .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pPagosLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPagosLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lCarnet2)
                                    .addGroup(pPagosLayout.createSequentialGroup()
                                        .addComponent(yc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pPagosLayout.setVerticalGroup(
            pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPagosLayout.createSequentialGroup()
                .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pPagosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pPagosLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lCarnet2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pagos", pPagos);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setText("Tipo:");

        cbTipoSocio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTipoSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoSocioActionPerformed(evt);
            }
        });

        btnEliminarSocio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEliminarSocio.setText("Eliminar");
        btnEliminarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(lCarnet1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTipoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfApellido)
                                        .addComponent(tfTelefono)
                                        .addComponent(tfDireccion)
                                        .addComponent(dcFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dcFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addComponent(tfCI, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnActualizar)
                                .addGap(51, 51, 51)
                                .addComponent(btnEliminarSocio)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCarnet1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tfCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminarSocio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCIActionPerformed

    private void tfCIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCIKeyPressed
        // TODO add your handling code here:
        if(evt.equals("a"))
            evt.consume();
    }//GEN-LAST:event_tfCIKeyPressed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        s.setFechaIngreso(dcFechaIngreso.getDate());
        s.setNombre(tfNombre.getText());
        s.setApellido(tfApellido.getText());
        s.setTelefono(tfTelefono.getText());
        s.setFechaNac(dcFechaNac.getDate());
        //s.setRol(cbRol.getSelectedItem().toString());
        s.setTipo((TipoSocio)cbTipoSocio.getSelectedItem());
        Conexion.getInstance().merge(s);
        JOptionPane.showMessageDialog(this, "Datos actualizados.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void cbTipoSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoSocioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbTipoSocioActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        if(s != null){
            switch (jTabbedPane1.getSelectedIndex()){
                case 1:
                    loadAct();
                break;
                case 2:
                    loadCuotas();
                    loadCB();
                break;
                case 3:
                    loadFamilia();
                break;
                case 4:
                    cargarPagos();
                break;
                case 0:
                    if(j != null)
                        loadJugador();
                break;
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(tPagos.getSelectedRowCount()==1){
            if (JOptionPane.showConfirmDialog(this, "¿Seguro de que quiere eliminar este producto?", "Consulta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                PagoBBC p = (PagoBBC) tPagos.getValueAt(tPagos.getSelectedRow(), 1);
                Conexion.getInstance().delete(p);//pedir confirmacion
                cargarPagos();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if((int)sMonto.getValue()!=0){
            PagoBBC p = new PagoBBC();
            p.setSocio(s);
            p.setFecha(new Date());
            p.setMonto((int)sMonto.getValue());
            Conexion.getInstance().persist(p);
            cargarPagos();
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPagosMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tPagosMouseClicked

    private void btnAgregarNuevoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNuevoFActionPerformed
        // TODO add your handling code here:
        main.AbrirAltaSocio(new AltaSocio(main,s.getFamilia()));
    }//GEN-LAST:event_btnAgregarNuevoFActionPerformed

    private void btnEliminarFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFamiliarActionPerformed
        // TODO add your handling code here:
        if(tFamiliares.getSelectedRowCount()==1 && tFamiliares.getRowCount()>1 && JOptionPane.showConfirmDialog(this, "¿Seguro de que quiere eliminar este miebro de la familia?", "Consulta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            Socio eliFamiliar = (Socio) tFamiliares.getValueAt(tFamiliares.getSelectedRow(), 0);
            Familia f = new Familia();
            Conexion.getInstance().persist(f);
            eliFamiliar.setFamilia(f);
            Conexion.getInstance().merge(eliFamiliar);
            DefaultTableModel dtm = (DefaultTableModel) tFamiliares.getModel();
            dtm.removeRow(tFamiliares.getSelectedRow());
            JOptionPane.showMessageDialog(this, "Miembro eliminado de la familia.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarFamiliarActionPerformed

    private void btnAgregarCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCuotaActionPerformed
        // TODO add your handling code here:
        Cuota cuota = (Cuota) cbCuotas.getSelectedItem();
        if(cuota.getSocios()!=null){
            cuota.getSocios().add(s);
        }
        s.getCuotas().add(cuota);
        Conexion.getInstance().merge(cuota);
        //s.getCuotas().add( (Cuota) cbCuotas.getSelectedItem());
        cbCuotas.removeItem(cbCuotas.getSelectedItem());
        DefaultTableModel mdl = (DefaultTableModel) tCuotas.getModel();

        Object[] fila = new Object[4];
        fila[0] = Conexion.sdf.format(cuota.getFecha());
        fila[1] = cuota;
        fila[2] = cuota.getDescripcion();
        fila[3] = cuota.getMonto();
        mdl.addRow(fila);

        //loadCuotas();
    }//GEN-LAST:event_btnAgregarCuotaActionPerformed

    private void btnEliminarCuotaDeSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCuotaDeSocioActionPerformed
        // TODO add your handling code here:
        if(tCuotas.getSelectedRowCount()==1){
            if (JOptionPane.showConfirmDialog(this, "¿Seguro de que quiere eliminar esta cuota?", "Consulta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                Cuota c = (Cuota) tCuotas.getValueAt(tCuotas.getSelectedRow(), 1);
                s.getCuotas().remove(c);
                c.getSocios().remove(s);
                Conexion.getInstance().merge(s);
                Conexion.getInstance().merge(c);
                DefaultTableModel mdl = (DefaultTableModel) tCuotas.getModel();
                mdl.removeRow(tCuotas.getSelectedRow());
            }
        }
    }//GEN-LAST:event_btnEliminarCuotaDeSocioActionPerformed

    private void btnAgregarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActividadActionPerformed
        // TODO add your handling code here:
        AsociarActividad asac = new AsociarActividad(main,s,null);
        Principal.AbrirAsociarActividad(asac);
    }//GEN-LAST:event_btnAgregarActividadActionPerformed

    private void tCuotasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCuotasKeyReleased
        // TODO add your handling code here:
        
        if(tFamiliares.getSelectedRowCount()==1){
            Socio so = (Socio) tFamiliares.getValueAt(tFamiliares.getSelectedRow(), 0);
            DetallesSocio dj = new DetallesSocio(main,so);
            main.AbrirDetallesJugador(dj);
        }
    }//GEN-LAST:event_tCuotasKeyReleased

    private void btnEliminarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSocioActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "¿Seguro de que quiere eliminar este socio?", "Consulta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            s.setVigente(false);
            Conexion.getInstance().merge(s);
            main.AbrirVerSocios(new VerSocios(main));
        }
    }//GEN-LAST:event_btnEliminarSocioActionPerformed

    private void btnModificarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActividadActionPerformed
        // TODO add your handling code here:
        if(tActividades.getSelectedRowCount()==1){
            AsociarActividad asac = new AsociarActividad(main,s, (SocioActividad) tActividades.getValueAt(tActividades.getSelectedRow(), 1));
            Principal.AbrirAsociarActividad(asac);
        }
    }//GEN-LAST:event_btnModificarActividadActionPerformed

    private void cbCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCatActionPerformed

    private void cbTipoCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoCarnetActionPerformed

    private void btnActualizarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarJugadorActionPerformed
        // TODO add your handling code here:
        j.setCarnetHabilitante(dcVenCarnet.getDate());
        j.setPlantel((Categoria)cbCat.getSelectedItem());
        j.setTipoCarnet(cbTipoCarnet.getSelectedIndex());
        j.setVenCi(dcVenCi.getDate());
        j.setDetalles(taDesc.getText());
        Conexion.getInstance().merge(s);
        JOptionPane.showMessageDialog(this, "Datos de jugador actualizados.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnActualizarJugadorActionPerformed

    private void btnBorrarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActividadActionPerformed
        // TODO add your handling code here:
        if(tActividades.getSelectedRowCount()==1){
            if (JOptionPane.showConfirmDialog(this, "¿Seguro de que quiere eliminar esta actividad de la tabla?", "Consulta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                SocioActividad sa = (SocioActividad) tActividades.getValueAt(tActividades.getSelectedRow(), 1);
                Conexion.getInstance().delete(sa);
                DefaultTableModel mdl = (DefaultTableModel) tActividades.getModel();
                mdl.removeRow(tActividades.getSelectedRow());
            }
        }
    }//GEN-LAST:event_btnBorrarActividadActionPerformed

    private void btnAgregarExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarExistenteActionPerformed
        // TODO add your handling code here:
        if(!esCIValida(tfCi.getText()))
            JOptionPane.showMessageDialog(this, "Cédula invalida.", "Error", JOptionPane.ERROR_MESSAGE);
        else{
            Socio s2 = Conexion.getInstance().findSocio(Integer.valueOf(tfCi.getText()));
            if(s2==null)
                JOptionPane.showMessageDialog(this, "No existe un socio con esta cédula en el sistema.", "Error", JOptionPane.ERROR_MESSAGE);
            else if(!s2.isVigente())
                JOptionPane.showMessageDialog(this, "Este socios está dado de baja en el sistema.", "Error", JOptionPane.ERROR_MESSAGE);
            else if(tFamiliares.getRowCount()>3)
                JOptionPane.showMessageDialog(this, "Esta familia está llena.", "Error", JOptionPane.ERROR_MESSAGE);
            else{
                if(s2.getFamilia().getSocios().size()>1){
                    if(s2.getRol()){
                        if(s2.getFamilia().getSocios().get(0)==s2)
                            s2.getFamilia().getSocios().get(0).setRol(true);
                        else
                            s2.getFamilia().getSocios().get(1).setRol(true);
                    }
                    s2.setFamilia(s.getFamilia());
                    s2.setRol(false);
                    Conexion.getInstance().merge(s2);
                    addFamiliar(s2);
                    JOptionPane.showMessageDialog(this, "Familiar Agregado.", "Información", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    Familia fami = s2.getFamilia();
                    s2.setFamilia(s.getFamilia());
                    s2.setRol(false);
                    Conexion.getInstance().merge(s2);
                    Conexion.getInstance().delete(fami);
                    addFamiliar(s2);
                    JOptionPane.showMessageDialog(this, "Familiar Agregado.", "Información", JOptionPane.INFORMATION_MESSAGE);
                    /*List<PagoBBC> pagos = new ArrayList<PagoBBC>();
                    Iterator<PagoBBC> it = s2.getFamilia().getPagos().iterator();
                    while(it.hasNext()){
                        PagoBBC p = (PagoBBC) it.next();
                        p.setFamilia(s.getFamilia());
                        pagos.add(p);
                        //Conexion.getInstance().merge(p);
                    }
                    s.getFamilia().getPagos().addAll(pagos);
                    s2.setRol(false);
                    s2.setFamilia(s.getFamilia());
                    Conexion.getInstance().merge(s2);
                    Conexion.getInstance().delete(s2.getFamilia());
                    addFamiliar(s2);*/
                }
            }
        }
    }//GEN-LAST:event_btnAgregarExistenteActionPerformed

    private void btnDetallesFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesFamiliarActionPerformed
        // TODO add your handling code here:
        if(tFamiliares.getSelectedRowCount()==1){
            Socio so = (Socio)tFamiliares.getValueAt(tFamiliares.getSelectedRow(), 1);
            DetallesSocio dj = new DetallesSocio(main,so);
            main.AbrirDetallesJugador(dj);
        }
    }//GEN-LAST:event_btnDetallesFamiliarActionPerformed

    private void tFamiliaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tFamiliaresMouseClicked
        // TODO add your handling code here:       
        if(tFamiliares.getSelectedRowCount()==1){
            if(tFamiliares.getRowCount()>1 && (boolean) tFamiliares.getValueAt(tFamiliares.getSelectedRow(), 3)){
                Socio soci = (Socio) tFamiliares.getValueAt(tFamiliares.getSelectedRow(), 0);
                soci.setRol(true);
                Conexion.getInstance().merge(soci);
                for(int i=0; i < tFamiliares.getRowCount();i++){
                    if(i!=tFamiliares.getSelectedRow()){
                        Socio soci2 = (Socio) tFamiliares.getValueAt(i, 0);
                        soci2.setRol(false);
                        Conexion.getInstance().merge(soci2);
                        tFamiliares.setValueAt(false, i, 3);
                    }
                }
            }
            else{
                tFamiliares.setValueAt(true, tFamiliares.getSelectedRow(), 3);
            }
            
        }
    }//GEN-LAST:event_tFamiliaresMouseClicked
    
    public void addFamiliar(Socio s3){
        DefaultTableModel mdl = (DefaultTableModel) tFamiliares.getModel();
        Object[] fila = new Object[4];
        fila[0] = s3;
        fila[1] = s3.getApellido();
        fila[2] = s3.getFechaNac();
        fila[3] = s3.getRol();
        mdl.addRow(fila); 
    }
    public void cargarPagos(){
        Conexion.getInstance().refresh(s);
        Iterator<PagoBBC> it = s.getPagos().iterator();
        DefaultTableModel mdl = (DefaultTableModel) tPagos.getModel();
        mdl.setRowCount(0);
        while (it.hasNext()) {
            PagoBBC sa = it.next();
            if (sa.getFecha().getYear() == yc.getYear() && sa.getFecha().getMonth() == mc.getMonth()) {  
                Object[] fila = new Object[2];
                fila[0] = Conexion.sdf.format(sa.getFecha());
                fila[1] = sa;
                mdl.addRow(fila); 
            }
        }
    }
    public void loadAct(){
        Iterator<SocioActividad> it = Conexion.getInstance().getActAsociadas( Integer.toString(s.getCi())).iterator();
        DefaultTableModel mdl = (DefaultTableModel) tActividades.getModel();
        mdl.setRowCount(0);
        while (it.hasNext()) {
            SocioActividad sa = it.next();
            //if (s.isVigente()) {  
                Object[] fila = new Object[4];
                fila[0] = sa.getActividades();
                fila[1] = sa;
                fila[2] = sa.getActividades().getCupos();
                mdl.addRow(fila); 
            //}
        }
    }
    
    public void loadCuotas(){
        if(s.getCuotas().size()>0){
            Iterator<Cuota> it = s.getCuotas().iterator();
            DefaultTableModel mdl = (DefaultTableModel) tCuotas.getModel();
            mdl.setRowCount(0);
            while (it.hasNext()) {
                Cuota sa = it.next();
                if (sa.isVigente()) {  
                    Object[] fila = new Object[4];
                    fila[0] = Conexion.sdf.format(sa.getFecha());
                    fila[1] = sa;
                    fila[2] = sa.getDescripcion();
                    fila[3] = sa.getMonto();
                    mdl.addRow(fila); 
                }
            }
        }
    }
    
    public void loadCB(){
        List<Cuota> act;
        act = Conexion.getInstance().getCuotas();
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        for(Cuota cliente: act){
            //if(cliente.isVigente()){
                dcm.addElement(cliente);
            //}
        }
        cbCuotas.setModel(dcm);
    }
    
    public void loadFamilia(){
        Conexion.getInstance().refresh(s.getFamilia());
        Iterator<Socio> it = s.getFamilia().getSocios().iterator();
        DefaultTableModel mdl = (DefaultTableModel) tFamiliares.getModel();
        mdl.setRowCount(0);
        while (it.hasNext()) {
            Socio s = it.next();
            if (s.isVigente()) {  
                Object[] fila = new Object[4];
                fila[0] = s;
                fila[1] = s.getApellido();
                fila[2] = s.getFechaNac();
                fila[3] = s.getRol();
                mdl.addRow(fila); 
            }
        }
    }
    
    public void loadJugador(){
        List<Categoria> ts;
        ts = Conexion.getInstance().getCategorias();
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        for(Categoria tipo: ts){
                if(tipo.isVigente()){
                        dcm.addElement(tipo);
                }
        }
        cbCat.setModel(dcm);
        cbCat.setSelectedItem(j.getPlantel());
        cbTipoCarnet.setSelectedIndex(j.getTipoCarnet());
        dcVenCi.setDate(j.getVenCi());
        dcVenCarnet.setDate(j.getCarnetHabilitante());
    }
    public static boolean esCIValida(String ci) {
        if(ci.length() != 7 && ci.length() != 8){
            return false;
        }
        else{
            try{
            Integer.parseInt(ci);
            }
            catch (NumberFormatException e){
                return false;
            }
        }

        int digVerificador = Integer.parseInt((ci.charAt(ci.length() - 1)) + "" ) ;
        int[] factores;
        if(ci.length() == 7){ // CI viejas
            factores = new int[]{9, 8, 7, 6, 3, 4};
        }
        else{
            factores = new int[]{2, 9, 8, 7, 6, 3, 4};
        }


        int suma = 0;
        //for(int i=0; i int digito = Integer.parseInt(ci.charAt(i) + "" ) ;
        for(int i = 0; i <ci.length()-1;i++){
            int digito = Integer.parseInt(ci.charAt(i) + "" );
            if(digito != 0)
                suma += digito * factores[ i ];
        }
        
        

        int resto = suma % 10;
        int checkdigit = 10 - resto;

        if(checkdigit == 10){
        return (digVerificador == 0);
        }
        else {
        return (checkdigit == digVerificador) ;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizarJugador;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarActividad;
    private javax.swing.JButton btnAgregarCuota;
    private javax.swing.JButton btnAgregarExistente;
    private javax.swing.JButton btnAgregarNuevoF;
    private javax.swing.JButton btnBorrarActividad;
    private javax.swing.JButton btnDetallesFamiliar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarCuotaDeSocio;
    private javax.swing.JButton btnEliminarFamiliar;
    private javax.swing.JButton btnEliminarSocio;
    private javax.swing.JButton btnModificarActividad;
    private javax.swing.JComboBox<String> cbCat;
    private javax.swing.JComboBox<String> cbCuotas;
    private javax.swing.JComboBox<String> cbTipoCarnet;
    private javax.swing.JComboBox<String> cbTipoSocio;
    private com.toedter.calendar.JDateChooser dcFechaIngreso;
    private com.toedter.calendar.JDateChooser dcFechaNac;
    private com.toedter.calendar.JDateChooser dcVenCarnet;
    private com.toedter.calendar.JDateChooser dcVenCi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lCarnet1;
    private javax.swing.JLabel lCarnet2;
    private com.toedter.calendar.JMonthChooser mc;
    private javax.swing.JPanel pActividades;
    private javax.swing.JPanel pCuotas;
    private javax.swing.JPanel pFamilia;
    private javax.swing.JPanel pJugador;
    private javax.swing.JPanel pPagos;
    private javax.swing.JSpinner sMonto;
    private javax.swing.JTable tActividades;
    private javax.swing.JTable tCuotas;
    private javax.swing.JTable tFamiliares;
    private javax.swing.JTable tPagos;
    private javax.swing.JTextArea taDesc;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCI;
    private javax.swing.JTextField tfCi;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    private com.toedter.calendar.JYearChooser yc;
    // End of variables declaration//GEN-END:variables
}
