/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import BD.Conexion;
import Clases.Jugador;
import Clases.Socio;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Integer.parseInt;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import static sun.security.x509.OIDMap.getClass;
/**
 *
 * @author nacho
 */

    

public class PrincipalBBC extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private static SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Resources/touringIco.png"));
        return retValue;
    }
    
    ImageIcon logo = new ImageIcon();
    AltaJugador abmSocios;
    public PrincipalBBC() {
        initComponents();
        cargarSocios();
        esJugador(false);
    }

    public void cargarSocios(){
        Iterator<Socio> it = Conexion.getInstance().getSocios().iterator();
        DefaultTableModel mdl = (DefaultTableModel) tSocios.getModel();
        mdl.setRowCount(0);
        while (it.hasNext()) {
            Socio s = it.next();
            if (s.isVigente()) {  
                Object[] fila = new Object[5];
                fila[0] = s;
                fila[1] = s.getApellido();
                fila[2] = s.getTelefono();
                fila[3] = s.getTipo();
                mdl.addRow(fila); 
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpSocios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tSocios = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        tfApellido = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        checkJugador = new javax.swing.JCheckBox();
        tfNombre = new javax.swing.JTextField();
        tfPlantel = new javax.swing.JTextField();
        lCarnet = new javax.swing.JLabel();
        lPlantel = new javax.swing.JLabel();
        dcCarnetHab = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        tfCedula = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dcFechaNac = new com.toedter.calendar.JDateChooser();
        jpReservas = new javax.swing.JPanel();
        jpHistorial = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(854, 480));
        setMinimumSize(new java.awt.Dimension(854, 480));
        setSize(new java.awt.Dimension(854, 480));

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jpSocios.setBackground(new java.awt.Color(255, 255, 255));
        jpSocios.setForeground(new java.awt.Color(255, 0, 255));
        jpSocios.setMaximumSize(new java.awt.Dimension(849, 453));
        jpSocios.setMinimumSize(new java.awt.Dimension(849, 453));

        tSocios.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Teléfono", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tSocios);

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAceptar.setText("Agregar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnModificar.setText("Modificar");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Socios");

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar");

        tfApellido.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        tfTelefono.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        tfDireccion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Teléfono:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Dirección:");

        checkJugador.setBackground(new java.awt.Color(255, 255, 255));
        checkJugador.setText("Jugador");
        checkJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkJugadorActionPerformed(evt);
            }
        });

        tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        tfPlantel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lCarnet.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lCarnet.setText("Carnet Hab.");

        lPlantel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lPlantel.setText("Plantel:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Cédula:");

        tfCedula.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCedulaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Fecha Nac.");

        javax.swing.GroupLayout jpSociosLayout = new javax.swing.GroupLayout(jpSocios);
        jpSocios.setLayout(jpSociosLayout);
        jpSociosLayout.setHorizontalGroup(
            jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSociosLayout.createSequentialGroup()
                .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSociosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(119, 119, 119))
                    .addGroup(jpSociosLayout.createSequentialGroup()
                        .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpSociosLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAceptar))
                            .addGroup(jpSociosLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpSociosLayout.createSequentialGroup()
                                        .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                            .addComponent(tfApellido)
                                            .addComponent(tfTelefono)
                                            .addComponent(tfDireccion)
                                            .addComponent(tfNombre)))
                                    .addComponent(checkJugador)
                                    .addGroup(jpSociosLayout.createSequentialGroup()
                                        .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lCarnet)
                                            .addComponent(lPlantel))
                                        .addGap(18, 18, 18)
                                        .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfPlantel)
                                            .addComponent(dcCarnetHab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSociosLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpSociosLayout.setVerticalGroup(
            jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
            .addGroup(jpSociosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(dcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkJugador)
                .addGap(8, 8, 8)
                .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSociosLayout.createSequentialGroup()
                        .addComponent(lCarnet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lPlantel)))
                    .addComponent(dcCarnetHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jpSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Socios", jpSocios);

        jpReservas.setBackground(new java.awt.Color(255, 255, 255));
        jpReservas.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpReservasLayout = new javax.swing.GroupLayout(jpReservas);
        jpReservas.setLayout(jpReservasLayout);
        jpReservasLayout.setHorizontalGroup(
            jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );
        jpReservasLayout.setVerticalGroup(
            jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reservas", jpReservas);

        jpHistorial.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpHistorialLayout = new javax.swing.GroupLayout(jpHistorial);
        jpHistorial.setLayout(jpHistorialLayout);
        jpHistorialLayout.setHorizontalGroup(
            jpHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );
        jpHistorialLayout.setVerticalGroup(
            jpHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Historial", jpHistorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCedulaActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if(checkJugador.isSelected()){
            Jugador j = new Jugador();
            j.setNombre(tfNombre.getText());
            j.setApellido(tfApellido.getText());
            j.setCi(parseInt(tfCedula.getText()));
            j.setDireccion(tfDireccion.getText());
            j.setFechaNac(dcFechaNac.getDate());
            j.setTelefono(tfTelefono.getText());
            j.setTipo("Jugador");
            j.setVigente(true);
            j.setCarnetHabilitante(dcCarnetHab.getDate());
            j.setPlantel(tfPlantel.getText());
            Conexion.getInstance().persist(j);
        }
        else{
            Socio s = new Socio();
            s.setNombre(tfNombre.getText());
            s.setApellido(tfApellido.getText());
            s.setCi(parseInt(tfCedula.getText()));
            s.setDireccion(tfDireccion.getText());
            s.setFechaNac(dcFechaNac.getDate());
            s.setTelefono(tfTelefono.getText());
            s.setTipo("Común");
            s.setVigente(true);
            Conexion.getInstance().persist(s);
        }
        cargarSocios();
        limpiar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void checkJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkJugadorActionPerformed
        // TODO add your handling code here:
        if(checkJugador.isSelected()==true){
            esJugador(true);
        }
        else{
            esJugador(false);
        }
    }//GEN-LAST:event_checkJugadorActionPerformed
    
    public void esJugador(boolean b){
        tfPlantel.setVisible(b);
        dcCarnetHab.setVisible(b);
        lCarnet.setVisible(b);
        lPlantel.setVisible(b);
    }
    
    public void limpiar(){
        tfNombre.setText("");
        tfApellido.setText("");
        tfDireccion.setText("");
        tfTelefono.setText("");
        tfPlantel.setText("");
        tfCedula.setText("");
        dcFechaNac.setDate(null);
        dcCarnetHab.setDate(null);
        checkJugador.setSelected(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalBBC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalBBC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalBBC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalBBC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalBBC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JCheckBox checkJugador;
    private com.toedter.calendar.JDateChooser dcCarnetHab;
    private com.toedter.calendar.JDateChooser dcFechaNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpHistorial;
    private javax.swing.JPanel jpReservas;
    private javax.swing.JPanel jpSocios;
    private javax.swing.JLabel lCarnet;
    private javax.swing.JLabel lPlantel;
    private javax.swing.JTable tSocios;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCedula;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPlantel;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
