/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import BD.Conexion;
import Clases.Jugador;
import Clases.Socio;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nacho
 */
public class VerSocios extends javax.swing.JPanel {

    /**
     * Creates new form PanelVacio
     */
    Principal main;
    Iterator<Socio> it;
    public VerSocios(Principal main) {
        initComponents();
        this.main=main;
        
        it = Conexion.getInstance().getSocios().iterator();
        cargarSocios();
    }
    
    public void cargarSocios(){
        DefaultTableModel mdl = (DefaultTableModel) tSocios.getModel();
        mdl.setRowCount(0);
        while (it.hasNext()) {
            Socio s = it.next();
            if (s.isVigente()) {  
                Object[] fila = new Object[4];
                fila[0] = s.getCi();
                fila[1] = s;
                fila[2] = s.getApellido();
                fila[3] = s.getTelefono();
                mdl.addRow(fila); 
            }
        }
    }
    
    public void buscarSocios(String buscar){
        DefaultTableModel mdl = (DefaultTableModel) tSocios.getModel();
        mdl.setRowCount(0);
        while (it.hasNext()) {
            Socio s = it.next();
            if (s.isVigente() && (s.getNombre().contains(buscar) || s.getApellido().contains(buscar) || s.getCi() == Integer.parseInt(buscar))) {  
                Object[] fila = new Object[4];
                fila[0] = s.getCi();
                fila[1] = s;
                fila[2] = s.getApellido();
                fila[3] = s.getTelefono();
                mdl.addRow(fila); 
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tSocios = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        tfBuscar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBuscarKeyPressed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tSocios.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Apellido", "Teléfono", "Dirección"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tSociosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tSocios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tSociosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tSociosMousePressed
        // TODO add your handling code here:
        if(tSocios.getSelectedRowCount()==1){
            DetallesSocio dj = new DetallesSocio(main,(Socio) tSocios.getValueAt(tSocios.getSelectedRow(), 1));

            main.AbrirDetallesJugador(dj);
        }
    }//GEN-LAST:event_tSociosMousePressed

    private void tfBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarKeyPressed
        // TODO add your handling code here:
        if(tfBuscar.getText().equals(""))
            cargarSocios();
        else
            buscarSocios(tfBuscar.getText());
    }//GEN-LAST:event_tfBuscarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tSocios;
    private javax.swing.JTextField tfBuscar;
    // End of variables declaration//GEN-END:variables
}
